language: ruby
rvm:
  - 1.8.7
  - 1.9.3
notifications:
  email:
   - dcleal@redhat.com
   - raphael.pinson@camptocamp.com
env:
  - PUPPET_VERSION=0.25.5
  - PUPPET_VERSION=2.6.17
  - PUPPET_VERSION=2.7.18
matrix:
  exclude:
    # No support for Ruby 1.9 before Puppet 2.7
    - rvm: 1.9.3
      env: PUPPET_VERSION=0.25.5
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.6.17
install:
  # Use latest Augeas
  - sudo add-apt-repository -y ppa:raphink/augeas
  - sudo apt-get update
  - sudo apt-get install libaugeas-dev libxml2-dev
  - sudo touch /etc/aliases
  - gem install bundler
  - bundle install
